= Pivotal Cloud Foundry 101 Workshop

== Schedule

This one day hands-on classroom style session will provide developers with hands on experience with Pivotal Cloud Foundry concepts, architecture and fundamentals of pushing code and building applications. The session includes presentations, demos and hands on labs

9:00 AM - 9:30 AM::
 * Session 1: _PCF 2.2 Overview for App Dev_ 
9:30 AM - 10:30 AM::
 * Lab1: Pushing your first app, Apps Manager_
10:30 AM - 10:45 AM:: Break
10:45 AM - 11:30 AM:: 
* Session 2: _Pivotal Cloud Foundry Services_
* Session 2: _Pivotal Cloud Cache_
11:30 AM - 12:30 PM:: Lunch Break
12:30 PM - 2:15 PM:: 
* Lab2 - Bind Cloudfoundry Services - Pivotal Cloud Cache and MySQL with your application
2:15 PM - 2:30 PM::
* Lab3 - Operate your application
2:30 PM - 2:45 PM:: 
* Lab4 - Monitor your application
2:45 PM - 3:00 PM:: Break
3:00 PM - 3:30 PM:: 
* Session 3: _Pivotal Cloud Foundry Security_
3:30 PM - 4:00 PM:: Demo - Spring Boot with Camel and Spring XML DSL on Pivotal Cloud Foundry
4:00 PM - 4:15 PM:: Wrap Up

== Course Materials

* Developer Workshop
** link:labs/lab1/lab.adoc[Lab 1 - From Zero to Pushing Your First Application]
** link:labs/lab2/lab.adoc[Lab 2 - Cloudfoundry Services with Pivotal Cloud Cache and MySQL]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]